"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts.
add_newline = true

[directory]
truncation_length = 5

[character]
success_symbol = '[➜](bold green)'
error_symbol = "[!](bold red)"

[git_status]
disabled = true

[git_branch]
symbol = ' '

[gradle]
symbol = ' '

[kotlin]
symbol = ' '

[package]
disabled = true
